### PR TITLE
fix formatting in js file

### PR DESCRIPTION
**Pull request by B3none**

### CODE REVIEW

**Comment by WardPearce** [comment]
I'll add this to the new release.

**Comment by B3none** [comment]
I'm going to put in a PR re-vamping the web code-wise. Do you know how to use `composer`?

**Comment by WardPearce** [comment]
Already, improving the site code. Can't see composer being really that necessary.

**Comment by B3none** [comment]
Using composer would just be to handle the routing as seen in: https://github.com/b3none/sharex

**Pull request merged**
